#!/usr/bin/env python3
"""Session-length feasibility check for split-creator programs.

Rest times are standardized at 2 minutes for every exercise in every
generated program (SKILL.md Step 3, stage 3). This script estimates each
session's wall-clock length from hard-set counts and flags any session over
the lifter's max session length (intake Q6).

Time model (per session):
  6 min   general warm-up / transitions baseline
  45 s    per working set (execution + breathing)
  2 min   rest after each set, except the last set of the session;
          a superset pair shares one rest (saves one 2-min rest per pair)
  1.5 min extra transition per exercise beyond the first

Usage:
  python3 .agents/skills/split-creator/scripts/session-length.py length.json
  cat length.json | python3 .agents/skills/split-creator/scripts/session-length.py -

Input JSON:
  {
    "target_min": 75,
    "sessions": {
      "U1": {"sets": 15, "superset_pairs": 0, "exercises": 6},
      "U2": {"sets": 17, "superset_pairs": 2, "exercises": 8}
    }
  }
  "exercises" is optional (defaults to ceil(sets / 2.5)).

Output: a markdown table for the program's session-length check plus
warnings for sessions over target. Exit codes: 0 = checked, 2 = bad input.
"""
import json
import math
import os
import sys

WARMUP_MIN = 6.0
SET_MIN = 0.75
REST_MIN = 2.0
TRANSITION_MIN = 1.5


def die(msg):
    sys.stderr.write("error: %s\n" % msg)
    sys.exit(2)


def read_input(path):
    if path == "-":
        try:
            return json.load(sys.stdin)
        except ValueError as exc:
            die("invalid JSON on stdin: %s" % exc)
    try:
        with open(path) as fh:
            return json.load(fh)
    except (OSError, ValueError) as exc:
        die("cannot read %s: %s" % (path, exc))


def estimate(sets, superset_pairs, exercises):
    if sets <= 0:
        return 0.0
    rests = max(sets - superset_pairs - 1, 0)
    transitions = TRANSITION_MIN * max(exercises - 1, 0)
    return WARMUP_MIN + sets * SET_MIN + rests * REST_MIN + transitions


def main():
    args = sys.argv[1:]
    if not args or args[0] in ("-h", "--help"):
        print(__doc__)
        return
    if len(args) != 1:
        die("usage: session-length.py <length.json | ->")
    data = read_input(args[0])
    if not isinstance(data, dict) or not isinstance(data.get("sessions"), dict):
        die('input must be {"target_min": N, "sessions": {name: {sets, ...}}}')

    target = data.get("target_min")
    if not isinstance(target, (int, float)) or target <= 0:
        die("target_min must be a positive number")

    rows, warnings = [], []
    for name in data["sessions"]:
        entry = data["sessions"][name]
        if isinstance(entry, int):
            entry = {"sets": entry}
        if not isinstance(entry, dict):
            die("%s: expected integer or object with sets/superset_pairs/exercises" % name)
        sets = entry.get("sets")
        if not isinstance(sets, int) or isinstance(sets, bool) or sets < 0:
            die("%s: sets must be a non-negative integer" % name)
        pairs = entry.get("superset_pairs", 0)
        if not isinstance(pairs, int) or isinstance(pairs, bool) or pairs < 0:
            die("%s: superset_pairs must be a non-negative integer" % name)
        if pairs * 2 > sets:
            die("%s: more superset pairs than sets" % name)
        exercises = entry.get("exercises") or max(1, math.ceil(sets / 2.5))
        if not isinstance(exercises, int) or exercises < 1:
            die("%s: exercises must be a positive integer" % name)
        minutes = estimate(sets, pairs, exercises)
        over = minutes > target
        rows.append((name, sets, pairs, exercises, minutes, over))
        if over:
            warnings.append(
                "%s: ~%d min exceeds the %d-min session budget — cut sets, "
                "merge exercises into supersets, or move work to another day"
                % (name, round(minutes), target)
            )

    print("## Session-length check (generated by session-length.py)\n")
    print("| Session | Hard sets | Superset pairs | Exercises | Est. length | Verdict |")
    print("|---|---|---|---|---|---|")
    for name, sets, pairs, exercises, minutes, over in rows:
        verdict = "🚨 over budget" if over else "✅ fits"
        print(
            "| %s | %d | %d | %d | ~%d min | %s |"
            % (name, sets, pairs, exercises, round(minutes), verdict)
        )
    print()
    if warnings:
        print("**Warnings**\n")
        for warning in warnings:
            print("- %s" % warning)
    else:
        print("All sessions fit the %d-min budget at the standardized 2-min rest." % target)
    print(
        "\n*Model: 6 min warm-up + 45 s/set + 2-min rests (one shared rest per "
        "superset pair, none after the last set) + 1.5 min transition per "
        "additional exercise. Estimate, not a stopwatch — reconcile against "
        "the session tables before shipping.*"
    )


if __name__ == "__main__":
    main()
